config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  resources :admin_user_posts
  resources :user_posts
  get 'static_pages/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
end

app/models/user_post.rb
class UserPost < ApplicationRecord
end

app/controllers/user_posts_controller.rb
class UserPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_post, only: %i[ show edit update destroy ]

  # GET /user_posts or /user_posts.json
  def index
    @user_posts = UserPost.all
  end

  # GET /user_posts/1 or /user_posts/1.json
  def show
  end

  # GET /user_posts/new
  def new
    @user_post = UserPost.new
  end

  # GET /user_posts/1/edit
  def edit
  end

  # POST /user_posts or /user_posts.json
  def create
    @user_post = UserPost.new(user_post_params)

    respond_to do |format|
      if @user_post.save
        format.html { redirect_to @user_post, notice: "User post was successfully created." }
        format.json { render :show, status: :created, location: @user_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_posts/1 or /user_posts/1.json
  def update
    respond_to do |format|
      if @user_post.update(user_post_params)
        format.html { redirect_to @user_post, notice: "User post was successfully updated." }
        format.json { render :show, status: :ok, location: @user_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_posts/1 or /user_posts/1.json
  def destroy
    @user_post.destroy
    respond_to do |format|
      format.html { redirect_to user_posts_url, notice: "User post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_post
      @user_post = UserPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_post_params
      params.require(:user_post).permit(:title, :body)
    end
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/views/user_posts/_form.html.erb
<%= form_with(model: user_post) do |form| %>
  <% if user_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_post.errors.count, "error") %> prohibited this user_post from being saved:</h2>

      <ul>
        <% user_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_posts/edit.html.erb
<h1>Editing User Post</h1>

<%= render 'form', user_post: @user_post %>

<%= link_to 'Show', @user_post %> |
<%= link_to 'Back', user_posts_path %>

app/views/user_posts/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
<h1>User Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_posts.each do |user_post| %>
      <tr>
        <td><%= user_post.title %></td>
        <td><%= user_post.body %></td>
        <td><%= link_to 'Show', user_post %></td>
        <td><%= link_to 'Edit', edit_user_post_path(user_post) %></td>
        <td><%= link_to 'Destroy', user_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Post', new_user_post_path %>

app/views/user_posts/new.html.erb
<h1>New User Post</h1>

<%= render 'form', user_post: @user_post %>

<%= link_to 'Back', user_posts_path %>

app/views/user_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @user_post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @user_post.body %>
</p>

<%= link_to 'Edit', edit_user_post_path(@user_post) %> |
<%= link_to 'Back', user_posts_path %>