config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  resources :admin_user_posts
  resources :user_posts
  get 'static_pages/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
end

app/models/admin_user_post.rb
class AdminUserPost < ApplicationRecord
end

app/controllers/admin_user_posts_controller.rb
class AdminUserPostsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :set_admin_user_post, only: %i[ show edit update destroy ]

  # GET /admin_user_posts or /admin_user_posts.json
  def index
    @admin_user_posts = AdminUserPost.all
  end

  # GET /admin_user_posts/1 or /admin_user_posts/1.json
  def show
  end

  # GET /admin_user_posts/new
  def new
    @admin_user_post = AdminUserPost.new
  end

  # GET /admin_user_posts/1/edit
  def edit
  end

  # POST /admin_user_posts or /admin_user_posts.json
  def create
    @admin_user_post = AdminUserPost.new(admin_user_post_params)

    respond_to do |format|
      if @admin_user_post.save
        format.html { redirect_to @admin_user_post, notice: "Admin user post was successfully created." }
        format.json { render :show, status: :created, location: @admin_user_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_user_posts/1 or /admin_user_posts/1.json
  def update
    respond_to do |format|
      if @admin_user_post.update(admin_user_post_params)
        format.html { redirect_to @admin_user_post, notice: "Admin user post was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_user_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_user_posts/1 or /admin_user_posts/1.json
  def destroy
    @admin_user_post.destroy
    respond_to do |format|
      format.html { redirect_to admin_user_posts_url, notice: "Admin user post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user_post
      @admin_user_post = AdminUserPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_user_post_params
      params.require(:admin_user_post).permit(:title, :body)
    end
end

app/helpers/admin_user_posts_helper.rb
module AdminUserPostsHelper
end

app/views/admin_user_posts/_form.html.erb
<%= form_with(model: admin_user_post) do |form| %>
  <% if admin_user_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_user_post.errors.count, "error") %> prohibited this admin_user_post from being saved:</h2>

      <ul>
        <% admin_user_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin_user_posts/edit.html.erb
<h1>Editing Admin User Post</h1>

<%= render 'form', admin_user_post: @admin_user_post %>

<%= link_to 'Show', @admin_user_post %> |
<%= link_to 'Back', admin_user_posts_path %>

app/views/admin_user_posts/index.html.erb
< id="notice"><%= notice %></>
<%= link_to 'ログアウト', destroy_admin_user_session_path, method: :delete %>
<h1>Admin User Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_user_posts.each do |admin_user_post| %>
      <tr>
        <td><%= admin_user_post.title %></td>
        <td><%= admin_user_post.body %></td>
        <td><%= link_to 'Show', admin_user_post %></td>
        <td><%= link_to 'Edit', edit_admin_user_post_path(admin_user_post) %></td>
        <td><%= link_to 'Destroy', admin_user_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin User Post', new_admin_user_post_path %>

app/views/admin_user_posts/new.html.erb
<h1>New Admin User Post</h1>

<%= render 'form', admin_user_post: @admin_user_post %>

<%= link_to 'Back', admin_user_posts_path %>

app/views/admin_user_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_user_post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @admin_user_post.body %>
</p>

<%= link_to 'Edit', edit_admin_user_post_path(@admin_user_post) %> |
<%= link_to 'Back', admin_user_posts_path %>